version: "3.9"
services:
  sidback:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
  sidfront:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"